import { Check, Plus, Search, X as XIcon } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { KeywordBoard, TrendingStrip } from '../components/keyword-board'
import { PageHeader } from '../components/layout'
import { PlayButton } from '../components/play-button'
import { Badge, Btn, EmptyState, Modal, Progress, ScoreRing, Spinner, Tabs, VALIDATION_META, fmt, timeAgo } from '../components/ui'
import { useStore } from '../store'
import type { Keyword, Validation } from '../types'

type Tab = 'keywords' | 'hashtags' | 'scraped' | 'validation' | 'analysis'
const relTone = (n: number) => (n >= 70 ? 'text-good-ink' : n >= 40 ? 'text-warn' : 'text-critical-ink')

export function ContentIntelligence() {
  const s = useStore(useShallow((st) => ({ keywords: st.keywords, signals: st.keywordSignals, hashtags: st.hashtags, topHashtags: st.topHashtags, scraped: st.scraped, ideas: st.ideas, scrapeRun: st.scrapeRun, validating: st.validating, runValidation: st.runValidation, openTheater: st.openTheater, setValidation: st.setValidation, setHashtagValidation: st.setHashtagValidation, updateKeyword: st.updateKeyword, addKeyword: st.addKeyword, removeKeyword: st.removeKeyword, addIdeaFromItem: st.addIdeaFromItem, openReview: st.openReview, setPage: st.setPage, buildKnowledge: st.buildKnowledge, building: st.building })))
  const [tab, setTab] = useState<Tab>('keywords'); const [q, setQ] = useState(''); const [filter, setFilter] = useState<'all' | Validation>('all'); const [kwModal, setKwModal] = useState<null | Partial<Keyword>>(null)
  const pending = s.scraped.filter((x) => x.validation === 'pending').length
  const trending = s.signals.filter((x) => x.isTrending).sort((a, b) => (a.rank ?? 99) - (b.rank ?? 99))
  const list = useMemo(() => s.scraped.filter((it) => (filter === 'all' || it.validation === filter) && (!q || `${it.title} ${it.snippet ?? ''} ${it.sourceName ?? ''} ${it.keyword ?? ''}`.toLowerCase().includes(q.toLowerCase()))), [s.scraped, filter, q])
  const top8 = useMemo(() => s.scraped.filter((x) => x.validation === 'validated').sort((a, b) => b.relevance - a.relevance).slice(0, 8), [s.scraped])
  const busy = s.scrapeRun.running || s.validating
  return (
    <div>
      <PageHeader title="Content Intelligence" subtitle="Keywords, hashtags and every scraped item — with the verdict and the reason behind it." agents={['scraping', 'validation', 'analysis']} actions={<><Btn variant="ghost" onClick={() => s.runValidation()} disabled={busy} icon={s.validating ? <Spinner /> : undefined}>Validate ({pending})</Btn><PlayButton label="Run Scraping" hint="12 keywords" running={s.scrapeRun.running} progress={s.scrapeRun.progress} onClick={s.openTheater} /></>} />
      {busy && <div className="card mb-4 flex items-center gap-3 px-4 py-3 anim-fade-up"><Spinner /><span className="text-sm">{s.validating ? 'Validation Agent is re-scoring pending items…' : `Scraping Agent · scanning ${s.scrapeRun.currentKeyword || 'keywords'}`}</span><Progress value={s.validating ? 60 : s.scrapeRun.progress} className="ml-auto w-40" /></div>}
      <Tabs tabs={[{ id: 'keywords', label: 'Keywords', count: s.keywords.filter((k) => k.active).length }, { id: 'hashtags', label: 'Hashtags', count: s.hashtags.filter((h) => h.rank).length }, { id: 'scraped', label: 'Scraped Data', count: s.scraped.length }, { id: 'validation', label: 'Validation', count: s.scraped.filter((x) => x.validation === 'needs_review').length }, { id: 'analysis', label: 'AI Analysis', count: top8.length }]} value={tab} onChange={setTab} />
      <div className="mt-4">
        {tab === 'keywords' && <div className="space-y-4 anim-fade-up"><div className="flex items-center justify-between"><div className="text-sm font-semibold">Top 5 trending this week</div><Btn size="sm" variant="primary" icon={<Plus size={13} />} onClick={() => setKwModal({ term: '', category: 'Core', weight: 60 })}>Add keyword</Btn></div><TrendingStrip signals={s.signals} /><KeywordBoard keywords={s.keywords} signals={s.signals} onWeight={(id, w) => s.updateKeyword(id, { weight: w })} onToggle={(id, a) => s.updateKeyword(id, { active: a })} onEdit={(k) => setKwModal(k)} onDelete={(id) => s.removeKeyword(id)} /></div>}
        {tab === 'hashtags' && <div className="space-y-4 anim-fade-up">
          {trending.length === 0 && <EmptyState title="No trending keywords yet" body="Run the Scraping Agent to rank keywords and their hashtags." />}
          <div className="grid gap-3 xl:grid-cols-2 stagger-fade">{trending.map((t, i) => { const mine = s.hashtags.filter((h) => h.keywordId === t.keywordId && h.rank).sort((a, b) => (a.rank ?? 9) - (b.rank ?? 9)); return (
            <div key={t.id} className="card p-4" style={{ ['--i' as string]: i }}><div className="flex items-center justify-between"><div className="text-sm font-semibold"><span className="tabular mr-2 text-accent">#{t.rank}</span>{t.term}</div><Badge tone="magenta">trend {t.trendScore}</Badge></div>
              <table className="mt-2 w-full text-xs"><thead className="text-[10px] uppercase text-ink-3"><tr>{['#', 'Hashtag', 'Posts', 'Eng/post', 'Rel', 'Fresh', 'Score', 'Verdict', ''].map((h) => <th key={h} className="px-1.5 py-1 text-left font-medium">{h}</th>)}</tr></thead><tbody>{mine.length === 0 && <tr><td colSpan={9} className="px-1.5 py-2 text-ink-3">No hashtags ranked for this keyword yet.</td></tr>}{mine.map((h) => { const m = VALIDATION_META[h.validation]; return <tr key={h.id} className="border-t border-line/60"><td className="px-1.5 py-1.5"><span className="tabular grid h-5 w-5 place-items-center rounded bg-surface-3 text-[10px] font-semibold">{h.rank}</span></td><td className="px-1.5 py-1.5 font-medium">#{h.displayTag}</td><td className="tabular px-1.5 py-1.5">{h.postCount}</td><td className="tabular px-1.5 py-1.5">{fmt(h.engagementPerPost)}</td><td className={`tabular px-1.5 py-1.5 ${relTone(h.relevance)}`}>{h.relevance}%</td><td className="tabular px-1.5 py-1.5">{h.freshness}%</td><td className="tabular px-1.5 py-1.5 font-semibold">{h.hashtagScore}</td><td className="px-1.5 py-1.5"><Badge tone={m.tone} title={h.verdictReason ?? ''}>{m.label}</Badge>{h.validation === 'duplicate' && h.duplicateOfTag && <span className="ml-1 text-[10px] text-ink-3">→ merged into #{h.duplicateOfTag}</span>}</td><td className="px-1.5 py-1.5">{h.validation === 'needs_review' && <span className="flex gap-1"><button type="button" onClick={() => s.setHashtagValidation(h.id, 'validated')} className="rounded bg-good/20 p-1 text-good-ink" aria-label="Approve"><Check size={12} /></button><button type="button" onClick={() => s.setHashtagValidation(h.id, 'rejected')} className="rounded bg-critical/20 p-1 text-critical-ink" aria-label="Reject"><XIcon size={12} /></button></span>}</td></tr> })}</tbody></table></div>
          ) })}</div>
          <div className="card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-sm font-semibold">Top {s.topHashtags.length} · consolidated</div><div className="text-[11px] text-ink-3">De-duplicated across keywords and re-ranked globally — this is what the Knowledge Agent researches on Sunday.</div></div><Btn size="sm" variant="primary" disabled={s.building} icon={s.building ? <Spinner /> : undefined} onClick={() => s.buildKnowledge()}>Send to Knowledge Base</Btn></div>
            <div className="mt-3 flex flex-wrap items-end gap-2">{s.topHashtags.map((h, i) => <span key={h.id} title={`${h.keywordTerm} · score ${h.hashtagScore}${h.researchedAt ? ` · researched ${timeAgo(h.researchedAt)}` : ''}`} className="inline-flex items-center gap-1.5 rounded-full border border-accent/30 bg-accent/10 px-3 text-accent-bright" style={{ fontSize: `${Math.max(11, 18 - i * 0.3)}px`, lineHeight: 2 }}><span className="tabular text-[10px] text-ink-3">{i + 1}</span>#{h.displayTag}{h.researchedAt && <span className="text-[9px] text-good-ink">● {timeAgo(h.researchedAt)}</span>}</span>)}{s.topHashtags.length === 0 && <span className="text-xs text-ink-3">Run the pipeline to build the set.</span>}</div></div>
        </div>}
        {tab === 'scraped' && <div className="space-y-3 anim-fade-up"><div className="flex flex-wrap items-center gap-2"><label className="relative"><Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-ink-3" /><input placeholder="Search topics, sources…" value={q} onChange={(e) => setQ(e.target.value)} className="w-64 pl-8" /></label><div className="flex gap-1">{(['all', 'validated', 'needs_review', 'rejected', 'pending', 'duplicate'] as const).map((f) => <button key={f} type="button" onClick={() => setFilter(f)} className={`rounded-full border px-2.5 py-1 text-[11px] ${filter === f ? 'border-accent bg-accent/15 text-accent-bright' : 'border-line bg-surface-2 text-ink-2'}`}>{f === 'all' ? 'All' : VALIDATION_META[f].label}</button>)}</div></div>
          {list.length === 0 ? <EmptyState title="Nothing scraped yet" body="Run the Scraping Agent to pull LinkedIn posts for the keyword set." action={<Btn variant="primary" onClick={s.openTheater}>Run Scraping</Btn>} /> : <div className="card overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-[11px] uppercase tracking-wide text-ink-3"><tr className="border-b border-line">{['Topic', 'Source', 'Type', 'Keyword', 'Engagement', 'Relevance', 'Status', 'Scraped'].map((h) => <th key={h} className="px-3 py-2.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{list.map((it) => { const m = VALIDATION_META[it.validation]; const fresh = it.scrapedAt && Date.now() - Date.parse(it.scrapedAt) < 15 * 60000; return <tr key={it.id} className="border-b border-line/60 hover:bg-surface-2/60"><td className="max-w-md px-3 py-2"><div className="flex items-center gap-2 font-medium"><span className="truncate">{it.title}</span>{fresh && <Badge tone="magenta">NEW</Badge>}</div><div className="truncate text-xs text-ink-3">{it.snippet}</div></td><td className="px-3 py-2 text-xs">{it.sourceName}</td><td className="px-3 py-2"><Badge>{it.sourceType}</Badge></td><td className="px-3 py-2 text-xs">{it.keyword}</td><td className="tabular px-3 py-2">{fmt(it.engagement)}</td><td className={`tabular px-3 py-2 font-semibold ${relTone(it.relevance)}`}>{it.relevance}%</td><td className="px-3 py-2"><Badge tone={m.tone} title={it.verdictReason ?? ''}>{m.label}</Badge></td><td className="px-3 py-2 text-xs text-ink-3">Scraped {timeAgo(it.scrapedAt)}</td></tr> })}</tbody></table></div>}</div>}
        {tab === 'validation' && <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 stagger-fade anim-fade-up">{s.scraped.slice(0, 48).map((it, i) => { const m = VALIDATION_META[it.validation]; return (
          <div key={it.id} className="card p-4" style={{ ['--i' as string]: Math.min(i, 20) }}><div className="flex items-start justify-between gap-2"><div className="text-sm font-medium leading-snug line-clamp-2">{it.title}</div>{it.validation === 'pending' && s.validating ? <Spinner /> : <Badge tone={m.tone}>{m.label}</Badge>}</div><p className="mt-1 text-xs text-ink-3 line-clamp-2">{it.snippet}</p><div className="mt-3 grid grid-cols-3 gap-2 text-[11px]">{[['Source', it.sourceName], ['Credibility', it.credibility], ['Relevance', `${it.relevance}%`], ['Freshness', `${it.freshness}%`], ['Duplicate', it.isDuplicate ? 'Yes' : 'No'], ['Quality', Math.round((it.relevance + it.freshness + (it.credibility === 'High' ? 90 : it.credibility === 'Medium' ? 60 : 30)) / 3)]].map(([l, v]) => <div key={String(l)} className="rounded-md bg-surface-2 px-2 py-1.5"><div className="text-[9px] uppercase tracking-wide text-ink-3">{l}</div><div className="tabular font-medium">{v}</div></div>)}</div><p className="mt-2 text-[11px] text-ink-3">{it.verdictReason}</p>{it.validation === 'needs_review' && <div className="mt-3 flex gap-2"><Btn size="sm" variant="primary" icon={<Check size={12} />} onClick={() => s.setValidation(it.id, 'validated')}>Approve</Btn><Btn size="sm" variant="danger" icon={<XIcon size={12} />} onClick={() => s.setValidation(it.id, 'rejected')}>Reject</Btn></div>}</div>
        ) })}</div>}
        {tab === 'analysis' && <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4 stagger-fade anim-fade-up">{top8.map((it, i) => { const existing = s.ideas.find((x) => x.sourceItemId === it.id); const sig = s.signals.find((x) => x.keywordId === it.keywordId); const eng = it.engagement > 1500 ? 'High' : it.engagement > 500 ? 'Medium' : 'Low'; return (
          <div key={it.id} className="card flex flex-col p-4" style={{ ['--i' as string]: i }}><div className="flex items-start gap-3"><ScoreRing value={it.relevance} size={52} stroke={5} /><div className="min-w-0 text-sm font-medium leading-snug line-clamp-3">{it.title}</div></div><div className="mt-3 grid grid-cols-2 gap-1.5 text-[11px]">{[['Brand relevance', `${it.relevance}%`], ['Trend score', `${sig?.trendScore ?? '—'}`], ['Engagement', eng], ['Format', it.snippet && it.snippet.length > 400 ? 'Thought Leadership' : 'Short Post'], ['Platform', 'LinkedIn'], ['Best day', ['Tuesday', 'Wednesday', 'Thursday'][i % 3]]].map(([l, v]) => <div key={String(l)} className="rounded-md bg-surface-2 px-2 py-1"><div className="text-[9px] uppercase tracking-wide text-ink-3">{l}</div><div className="font-medium">{v}</div></div>)}</div><div className="mt-auto pt-3">{existing ? <Btn size="sm" variant="ghost" className="w-full" onClick={() => { s.setPage('calendar'); s.openReview(existing.id) }}>View in calendar</Btn> : <Btn size="sm" variant="primary" className="w-full" onClick={async () => { const id = await s.addIdeaFromItem(it.id); if (id) s.setPage('calendar') }}>Add to calendar</Btn>}</div></div>
        ) })}</div>}
      </div>
      <Modal open={kwModal !== null} onClose={() => setKwModal(null)} title={kwModal?.id ? 'Edit keyword' : 'Add keyword'} footer={<div className="flex justify-end gap-2"><Btn variant="ghost" onClick={() => setKwModal(null)}>Cancel</Btn><Btn variant="primary" disabled={!kwModal?.term || kwModal.term.trim().length < 2} onClick={async () => { if (!kwModal) return; if (kwModal.id) await s.updateKeyword(kwModal.id, { term: kwModal.term, category: kwModal.category, weight: kwModal.weight }); else await s.addKeyword({ term: kwModal.term!.trim(), category: kwModal.category ?? 'Core', weight: kwModal.weight ?? 60 }); setKwModal(null) }}>Save</Btn></div>}>
        {kwModal && <div className="space-y-3"><label className="block text-xs text-ink-2">Term<input value={kwModal.term ?? ''} onChange={(e) => setKwModal({ ...kwModal, term: e.target.value })} className="mt-1 w-full" /></label><label className="block text-xs text-ink-2">Category<select value={kwModal.category ?? 'Core'} onChange={(e) => setKwModal({ ...kwModal, category: e.target.value })} className="mt-1 w-full">{['Core', 'Adjacent', 'Positioning'].map((c) => <option key={c}>{c}</option>)}</select></label><label className="block text-xs text-ink-2">Weight · {kwModal.weight ?? 60}<input type="range" min={0} max={100} value={kwModal.weight ?? 60} onChange={(e) => setKwModal({ ...kwModal, weight: Number(e.target.value) })} className="mt-1 w-full" /></label></div>}
      </Modal>
    </div>
  )
}
