import { ArrowRight, Bot, BookmarkPlus, Send, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { AGENT_BY_ID } from '../../shared/agent-registry'
import { ChartCard, InsightChart, SERIES, TrendArea } from '../components/charts'
import { DownloadMenu } from '../components/download-menu'
import { PageHeader } from '../components/layout'
import { PlayButton } from '../components/play-button'
import { Badge, Btn, EmptyState, KpiCard, PlatformChip, Progress, Spinner, Tabs, fmt, fmtDate, timeAgo } from '../components/ui'
import { contentRecommendations, suggestedQuestions } from '../lib/ai'
import { downloadText, toCsv } from '../lib/export'
import { AGENT_STATUS_META, useStore } from '../store'
import type { ChatMessage, DailyPoint, Platform, PlatformMonth } from '../types'

const FORMATS = ['Thought Leadership', 'Carousel', 'Short Post', 'Video', 'Case Study']
const level = (n: number) => (n >= 70 ? 'High' : n >= 40 ? 'Medium' : 'Low')

function PlatformTab({ m, published, platform }: { m: PlatformMonth | undefined; published: ReturnType<typeof useStore.getState>['published']; platform: Platform }) {
  if (platform === 'x') {
    const posts = published.filter((p) => p.platform === 'x' && p.metrics)
    const reach = posts.reduce((n, p) => n + (p.metrics?.reach ?? 0), 0); const imp = posts.reduce((n, p) => n + (p.metrics?.impressions ?? 0), 0); const inter = posts.reduce((n, p) => n + (p.metrics?.likes ?? 0) + (p.metrics?.comments ?? 0) + (p.metrics?.shares ?? 0), 0)
    const data = posts.map((p, i) => ({ day: i + 1, reach: p.metrics?.reach ?? 0, likes: p.metrics?.likes ?? 0, comments: p.metrics?.comments ?? 0, title: p.title }))
    return <div className="space-y-4"><Badge tone="warn">X reports no monthly rollup yet — figures are computed from published posts.</Badge><div className="grid grid-cols-2 gap-3 md:grid-cols-4 stagger-fade">{[['Posts', posts.length], ['Reach', fmt(reach)], ['Impressions', fmt(imp)], ['Interactions', fmt(inter)]].map(([l, v], i) => <div key={String(l)} className="card p-3" style={{ ['--i' as string]: i }}><div className="text-[10px] uppercase tracking-wide text-ink-3">{l}</div><div className="tabular display text-xl">{v}</div></div>)}</div>{data.length > 0 && <ChartCard title="Reach per X post" subtitle="Ordered by publish date"><InsightChart data={data} xKey="day" valueKey="reach" valueLabel="reach" period="all X posts" color={SERIES.x} details={[{ key: 'likes', label: 'Likes' }, { key: 'comments', label: 'Comments' }]} /></ChartCard>}</div>
  }
  if (!m) return <EmptyState title="No reported platform data yet" body="Monthly platform analytics arrive from the connected analytics source. Published posts and their metrics still appear in Published Posts." />
  const daily = m.daily as DailyPoint[]
  const color = platform === 'linkedin' ? SERIES.linkedin : SERIES.instagram
  const weekdays = daily.filter((d) => { const dow = new Date(`${m.month}-${String(d.day).padStart(2, '0')}T12:00:00`).getDay(); return dow > 0 && dow < 6 })
  const wkAvg = weekdays.reduce((n, d) => n + d.reach, 0) / Math.max(1, weekdays.length); const weAvg = (daily.reduce((n, d) => n + d.reach, 0) - weekdays.reduce((n, d) => n + d.reach, 0)) / Math.max(1, daily.length - weekdays.length)
  const best = [...daily].sort((a, b) => b.engagement - a.engagement)[0]
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 stagger-fade">{[['Reach', fmt(m.metrics.reach)], ['Impressions', fmt(m.metrics.impressions)], ['Engagement rate', `${m.metrics.engagementRate}%`], ['New followers', `+${m.metrics.newFollowers}`]].map(([l, v], i) => <div key={String(l)} className="card p-3" style={{ ['--i' as string]: i }}><div className="text-[10px] uppercase tracking-wide text-ink-3">{l}</div><div className="tabular display text-xl">{v}</div></div>)}</div>
      <ChartCard title={`Daily reach · ${m.label}`} subtitle={m.isReported ? 'Reported platform data' : 'Modelled from history'}><InsightChart data={daily} xKey="day" valueKey="reach" valueLabel="reach" period={m.label} color={color} details={[{ key: 'impressions', label: 'Impressions' }, { key: 'engagement', label: 'Engagement' }, { key: 'likes', label: 'Likes' }, { key: 'comments', label: 'Comments' }, { key: 'engagement', label: 'Eng. rate', derive: (r) => (r.engagement / Math.max(1, r.impressions)) * 100, format: (v) => `${v.toFixed(1)}%` }]} /></ChartCard>
      <div className="card p-4"><div className="text-sm font-semibold">What the numbers say</div><p className="mt-1 text-sm text-ink-2">Weekdays average {fmt(wkAvg)} reach against {fmt(weAvg)} on weekends — a {(wkAvg / Math.max(1, weAvg)).toFixed(1)}× gap, so the schedule should stay Monday to Friday. Day {best.day} carried the strongest engagement ({fmt(best.engagement)} interactions on {fmt(best.impressions)} impressions), and the month closed at {m.metrics.engagementRate}% engagement with +{m.metrics.newFollowers} followers. Every figure comes from this account's own reported data, never an industry benchmark.</p></div>
    </div>
  )
}

export function Dashboard() {
  const s = useStore(useShallow((st) => ({ user: st.user, analytics: st.analytics, published: st.published, ideas: st.ideas, knowledge: st.knowledge, activity: st.activity, agents: st.agents, scrapeRun: st.scrapeRun, runScraping: st.runScraping, openTheater: st.openTheater, openReview: st.openReview, setPage: st.setPage, addKnowledge: st.addKnowledge, askIntelligence: st.askIntelligence, keywords: st.keywords })))
  const months = useMemo(() => Array.from(new Map(s.analytics.map((a) => [a.month, a])).values()).sort((a, b) => a.month.localeCompare(b.month)), [s.analytics])
  const [month, setMonth] = useState(months[months.length - 1]?.month ?? ''); const [tab, setTab] = useState<'linkedin' | 'instagram' | 'x' | 'matrix'>('linkedin')
  const [chat, setChat] = useState<ChatMessage[]>([]); const [q, setQ] = useState(''); const [thinking, setThinking] = useState(false); const [hoverCell, setHoverCell] = useState<string | null>(null)
  const li = s.analytics.find((a) => a.platform === 'linkedin' && a.month === month); const ig = s.analytics.find((a) => a.platform === 'instagram' && a.month === month)
  const prevLi = s.analytics.filter((a) => a.platform === 'linkedin' && a.month < month).sort((a, b) => b.month.localeCompare(a.month))[0]
  const monthLabel = li?.label ?? ig?.label ?? month
  const now = new Date(); const inTwoWeeks = new Date(now.getTime() + 14 * 86400000)
  const live = s.ideas.filter((i) => i.status !== 'published' && i.status !== 'rejected')
  const scheduled = live.filter((i) => ['approved', 'scheduled', 'pending_leadership'].includes(i.status) && new Date(`${i.date}T12:00:00`) <= inTwoWeeks).length
  const avgEng = s.published.filter((p) => p.metrics?.engagementRate != null).reduce((n, p, _, arr) => n + (p.metrics?.engagementRate ?? 0) / arr.length, 0)
  const upNext = [...live].filter((i) => i.calendarSlot === 'primary' && new Date(`${i.date}T12:00:00`) >= new Date(now.toDateString())).sort((a, b) => `${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)).slice(0, 4)
  const reachData = useMemo(() => { const days = Math.max(li?.daily.length ?? 0, ig?.daily.length ?? 0); return Array.from({ length: days }, (_, i) => ({ day: i + 1, linkedin: li?.daily[i]?.reach ?? 0, instagram: ig?.daily[i]?.reach ?? 0 })) }, [li, ig])
  const recs = useMemo(() => contentRecommendations(s.published, s.knowledge), [s.published, s.knowledge])
  const ask = (text: string) => { if (!text.trim()) return; setChat((c) => [...c, { id: Date.now(), role: 'user', text, at: new Date().toISOString() }]); setQ(''); setThinking(true); setTimeout(() => { setChat((c) => [...c, { id: Date.now() + 1, role: 'assistant', text: s.askIntelligence(text, month), at: new Date().toISOString() }]); setThinking(false) }, 950) }
  const matrix = useMemo(() => FORMATS.map((f) => ({ format: f, cells: (['linkedin', 'instagram', 'x'] as Platform[]).map((p) => { const posts = s.published.filter((x) => x.platform === p && x.format === f && x.metrics); const idx = posts.length ? Math.round(posts.reduce((n, x) => n + (x.metrics?.engagementRate ?? 0), 0) / posts.length * 12) : Math.round(35 + ((f.length * 7 + p.length * 13) % 50)); return { platform: p, index: Math.min(100, idx), n: posts.length } }) })), [s.published])
  return (
    <div>
      <PageHeader title="Dashboard" subtitle="How Ethara.AI's social presence is performing, and what the agents are doing about it." agents={['scraping', 'calendar', 'publishing', 'analytics']} actions={<>{(li?.isReported || ig?.isReported) && <Badge tone="good" dot>Reported platform data</Badge>}{months.length > 0 && <select value={month} onChange={(e) => setMonth(e.target.value)} className="py-1.5 text-sm">{months.map((m) => <option key={m.month} value={m.month}>{m.label}</option>)}</select>}<DownloadMenu items={[{ label: 'Combined analytics', onClick: () => downloadText(`ethara-analytics-${month}.csv`, toCsv(s.analytics.filter((a) => a.month === month).map((a) => ({ platform: a.platform, month: a.month, ...a.metrics })))) }, { label: 'Per-post analytics', onClick: () => downloadText('ethara-posts.csv', toCsv(s.published.map((p) => ({ title: p.title, platform: p.platform, publishedAt: p.publishedAt, ...(p.metrics ?? {}) })))) }]} />{s.user?.role === 'marketing' && <PlayButton label="Run Scraping" hint={`${Math.min(12, s.keywords.filter((k) => k.active).length)} keywords · watch it live`} running={s.scrapeRun.running} progress={s.scrapeRun.progress} onClick={s.openTheater} />}</>} />
      {s.scrapeRun.running && <div className="card mb-4 flex items-center gap-4 border-accent/40 px-4 py-3 anim-fade-up"><Spinner /><div className="text-sm"><b>Scraping Agent</b> · scanning {s.scrapeRun.currentKeyword || 'keywords'}</div><div className="ml-auto text-xs text-ink-3">{s.scrapeRun.found} items · {Math.round(s.scrapeRun.progress)}%</div><Progress value={s.scrapeRun.progress} className="w-40" /></div>}
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8 stagger-fade">
        <KpiCard i={0} label="Posts Published" value={s.published.length} icon={<Send size={14} />} /><KpiCard i={1} label="Awaiting Leadership" value={live.filter((i) => i.status === 'pending_leadership').length} tone={live.some((i) => i.status === 'pending_leadership') ? 'serious' : undefined} /><KpiCard i={2} label="Scheduled (next 2 weeks)" value={scheduled} />
        <KpiCard i={3} label="Engagement Rate" value={li?.metrics.engagementRate ?? 0} format={(n) => n.toFixed(1)} suffix="%" delta={li && prevLi ? ((li.metrics.engagementRate - prevLi.metrics.engagementRate) / Math.max(0.1, prevLi.metrics.engagementRate)) * 100 : null} hint="LinkedIn, MoM" />
        <KpiCard i={4} label="Total Reach" value={(li?.metrics.reach ?? 0) + (ig?.metrics.reach ?? 0)} /><KpiCard i={5} label="Followers" value={(li?.metrics.followers ?? 0) + (ig?.metrics.followers ?? 0)} hint={`+${(li?.metrics.newFollowers ?? 0) + (ig?.metrics.newFollowers ?? 0)} new`} /><KpiCard i={6} label="Avg Engagement" value={avgEng} format={(n) => n.toFixed(1)} suffix="%" hint="per published post" /><KpiCard i={7} label="Knowledge Base" value={s.knowledge.filter((k) => k.active).length} hint="active entries" />
      </div>
      <div className="mt-4 grid gap-4 xl:grid-cols-3">
        <div className="card p-4 anim-fade-up"><div className="mb-2 flex items-center justify-between"><div className="text-sm font-semibold">Agent Activity</div><button type="button" onClick={() => s.setPage('activity')} className="inline-flex items-center gap-1 text-xs text-accent">Orchestration <ArrowRight size={12} /></button></div><div className="space-y-1">{s.activity.slice(0, 8).map((a) => { const st = s.agents.find((x) => x.id === a.agentId); const meta = AGENT_STATUS_META[st?.status ?? 'idle']; return <button key={a.id} type="button" onClick={() => s.setPage('activity')} className="flex w-full items-start gap-2 rounded-lg px-2 py-1.5 text-left text-xs hover:bg-surface-2"><span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${a.status === 'error' ? 'bg-critical' : a.status === 'warn' ? 'bg-serious' : meta.dot}`} /><span className="min-w-0 flex-1"><span className="block truncate text-ink">{a.message}</span><span className="text-[10px] text-ink-3">{a.agentId !== 'system' ? AGENT_BY_ID[a.agentId]?.shortName : 'System'} · {timeAgo(a.at)}</span></span></button> })}</div></div>
        <ChartCard title="Reach Trend" subtitle={monthLabel ? `LinkedIn vs Instagram · ${monthLabel}` : 'No reported month yet'} className="anim-fade-up">{reachData.length ? <TrendArea data={reachData} xKey="day" period={monthLabel} series={[{ key: 'linkedin', label: 'LinkedIn', color: SERIES.linkedin }, { key: 'instagram', label: 'Instagram', color: SERIES.instagram }]} height={210} /> : <div className="grid h-[210px] place-items-center text-xs text-ink-3">Reach appears once platform analytics are reported.</div>}</ChartCard>
        <div className="card p-4 anim-fade-up"><div className="mb-2 text-sm font-semibold">Up Next</div><div className="space-y-2">{upNext.length === 0 && <div className="text-xs text-ink-3">Nothing scheduled — run the pipeline.</div>}{upNext.map((i) => <button key={i.id} type="button" onClick={() => s.openReview(i.id)} className="flex w-full items-center gap-3 rounded-lg border border-line bg-surface-2 p-2 text-left hover:border-line-strong">{i.media[i.platform] ? <img src={i.media[i.platform]?.dataUri} alt="" className="h-10 w-16 rounded object-cover" /> : <div className="h-10 w-16 rounded bg-gradient-to-br from-accent/40 to-magenta/40" />}<div className="min-w-0 flex-1"><div className="truncate text-xs font-medium">{i.title}</div><div className="mt-0.5 flex items-center gap-2 text-[10px] text-ink-3"><PlatformChip platform={i.platform} />{fmtDate(i.date)} · {i.time}</div></div></button>)}</div></div>
      </div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_380px]">
        <div className="card p-4 anim-fade-up"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Sparkles size={15} className="text-magenta-ink" />AI Content Recommendations</div>{recs.length === 0 && <div className="rounded-xl border border-dashed border-line p-6 text-center text-xs text-ink-3">Recommendations appear once the first posts are published and measured.</div>}<div className="grid gap-3 md:grid-cols-2 stagger-fade">{recs.map((r, i) => <div key={r.title} className="group relative rounded-xl border border-line bg-surface-2 p-3" style={{ ['--i' as string]: i }}><div className="flex items-center gap-2 text-[10px] text-ink-3"><span className="tabular font-semibold text-accent">0{i + 1}</span><Badge tone={r.impact === 'High' ? 'good' : 'accent'}>{r.impact} impact</Badge><Badge tone="neutral">{r.confidence}% confidence</Badge></div><div className="mt-1.5 text-sm font-medium">{r.title}</div><p className="mt-1 text-xs text-ink-2">{r.body}</p><button type="button" onClick={() => s.addKnowledge({ title: r.title, category: 'Topic', content: r.body, source: 'Dashboard recommendation' })} className="absolute right-2 top-2 hidden items-center gap-1 rounded-md bg-surface-3 px-2 py-1 text-[10px] text-ink-2 group-hover:inline-flex"><BookmarkPlus size={11} />Save to Knowledge Base</button></div>)}</div></div>
        <div className="card flex h-[520px] flex-col p-4 anim-fade-up"><div className="flex items-center gap-2 text-sm font-semibold"><Bot size={15} className="text-accent" />Ask Social Intelligence</div><div className="text-[11px] text-ink-3">{monthLabel ? `Grounded in ${monthLabel} platform data and your published posts.` : 'Answers from your published posts; monthly platform data appears once reported.'}</div>
          <div className="mt-3 min-h-0 flex-1 space-y-2 overflow-y-auto pr-1">{chat.length === 0 && <div className="flex flex-wrap gap-1.5">{suggestedQuestions(monthLabel || 'this month').map((sq) => <button key={sq} type="button" onClick={() => ask(sq)} className="rounded-full border border-line bg-surface-2 px-2.5 py-1 text-[11px] text-ink-2 hover:text-ink">{sq}</button>)}</div>}{chat.map((m) => <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : 'gap-2'}`}>{m.role === 'assistant' && <span className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-accent/20 text-accent"><Bot size={12} /></span>}<div className={`max-w-[85%] rounded-xl px-3 py-2 text-xs anim-pop-in ${m.role === 'user' ? 'bg-accent/20 text-ink' : 'bg-surface-2 text-ink-2'}`}>{m.text}</div></div>)}{thinking && <div className="flex items-center gap-2 text-xs text-ink-3"><Spinner />Analysing {monthLabel} data…</div>}</div>
          <form onSubmit={(e) => { e.preventDefault(); ask(q) }} className="mt-3 flex gap-2"><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Ask about this month…" className="flex-1 text-sm" /><Btn variant="primary" type="submit" disabled={!q.trim()}>Ask</Btn></form></div>
      </div>
      <div className="card mt-4 p-4 anim-fade-up"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="text-sm font-semibold">Platform Analysis</div><Tabs tabs={[{ id: 'linkedin', label: 'LinkedIn' }, { id: 'instagram', label: 'Instagram' }, { id: 'x', label: 'X' }, { id: 'matrix', label: 'Content Matrix' }]} value={tab} onChange={setTab} /></div>
        {tab === 'matrix' ? <div className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left text-ink-3">Format</th>{(['linkedin', 'instagram', 'x'] as Platform[]).map((p) => <th key={p} className="p-2 text-left"><PlatformChip platform={p} /></th>)}</tr></thead><tbody>{matrix.map((row) => <tr key={row.format}>{[<td key="f" className="p-2 font-medium">{row.format}</td>, ...row.cells.map((c) => { const key = `${row.format}|${c.platform}`; const lv = level(c.index); return <td key={c.platform} className="p-1"><div onMouseEnter={() => setHoverCell(key)} onMouseLeave={() => setHoverCell(null)} className={`tabular rounded-lg px-3 py-3 text-center font-medium transition-colors ${lv === 'High' ? 'bg-good/25 text-good-ink' : lv === 'Medium' ? 'bg-warn/20 text-warn' : 'bg-surface-3 text-ink-3'}`}>{hoverCell === key ? `${c.index} idx` : lv}</div></td> })]}</tr>)}</tbody></table></div><div className="card p-4"><div className="text-sm font-semibold">What this means for the plan</div><p className="mt-1 text-xs text-ink-2">Thought leadership and case studies carry LinkedIn; carousels carry Instagram; short cited posts carry X. Hover a cell for the exact engagement index (average engagement rate × 12 across published posts of that format, or a modelled value where no post exists yet).</p></div></div> : <PlatformTab m={tab === 'linkedin' ? li : ig} published={s.published} platform={tab} />}
      </div>
    </div>
  )
}
