import { BookmarkPlus, RefreshCw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { DownloadMenu } from '../components/download-menu'
import { PageHeader } from '../components/layout'
import { Badge, Btn, Modal, PLATFORM_COLOR, PLATFORM_LABEL, PlatformChip, PlatformIcon, Spinner, fmt, fmtDate } from '../components/ui'
import { downloadDataUri, downloadText, toCsv } from '../lib/export'
import { useStore } from '../store'
import type { Platform, PublishedPost } from '../types'

const PLATFORMS: Platform[] = ['linkedin', 'instagram', 'x']

export function PublishedPosts() {
  const s = useStore(useShallow((st) => ({ published: st.published, addKnowledge: st.addKnowledge, refreshAnalytics: st.refreshAnalytics, agents: st.agents })))
  const [platform, setPlatform] = useState<Platform>('linkedin'); const [open, setOpen] = useState<PublishedPost | null>(null)
  const posts = useMemo(() => s.published.filter((p) => p.platform === platform), [s.published, platform])
  const sum = (k: 'reach' | 'impressions' | 'likes' | 'comments' | 'shares') => posts.reduce((n, p) => n + (p.metrics?.[k] ?? 0), 0)
  const inter = sum('likes') + sum('comments') + sum('shares'); const avg = posts.filter((p) => p.metrics?.engagementRate != null).reduce((n, p, _, a) => n + (p.metrics?.engagementRate ?? 0) / a.length, 0)
  const best = [...posts].sort((a, b) => (b.metrics?.engagementRate ?? 0) - (a.metrics?.engagementRate ?? 0))[0]
  const refreshing = s.agents.find((a) => a.id === 'analytics')?.status === 'running'
  const rowCsv = (p: PublishedPost) => toCsv([{ title: p.title, platform: p.platform, publishedAt: p.publishedAt, ...(p.metrics ?? {}) }])
  return (
    <div>
      <PageHeader title="Published Posts" subtitle="Every post with its receipt, its latest metrics and the Analytics Agent's read against this account's own baseline." agents={['publishing', 'analytics']} actions={<Btn variant="ghost" icon={refreshing ? <Spinner /> : <RefreshCw size={14} />} disabled={refreshing} onClick={() => s.refreshAnalytics()}>Refresh metrics</Btn>} />
      <div className="mb-5 flex items-center justify-center gap-8 anim-fade-up">{PLATFORMS.map((p) => { const n = s.published.filter((x) => x.platform === p).length; const on = platform === p; return <button key={p} type="button" onClick={() => setPlatform(p)} className="relative grid place-items-center" aria-label={PLATFORM_LABEL[p]}>{on && <><span className="absolute inset-[-8px] rounded-full border" style={{ borderColor: PLATFORM_COLOR[p] }} /><span className="absolute inset-[-8px] rounded-full border anim-ping-slow" style={{ borderColor: PLATFORM_COLOR[p] }} /></>}<span className={`grid place-items-center rounded-full border border-line bg-surface-2 transition-all duration-300 ${on ? 'h-20 w-20' : 'h-14 w-14 opacity-70 hover:opacity-100'}`} style={on ? { boxShadow: `0 0 34px ${PLATFORM_COLOR[p]}55`, color: PLATFORM_COLOR[p] } : undefined}><PlatformIcon platform={p} size={on ? 30 : 20} /></span><span className="tabular absolute -right-1 -top-1 grid h-6 min-w-6 place-items-center rounded-full bg-accent px-1 text-[11px] font-semibold text-on-accent">{n}</span></button> })}</div>
      <div className="card mb-4 overflow-hidden anim-fade-up"><div className="h-1" style={{ background: PLATFORM_COLOR[platform] }} /><div className="grid gap-3 p-4 md:grid-cols-[repeat(4,1fr)_1.4fr]">{[['Posts', posts.length], ['Total Reach', fmt(sum('reach'))], ['Interactions', fmt(inter)], ['Avg. Engagement', `${avg.toFixed(1)}%`]].map(([l, v]) => <div key={String(l)} className="rounded-lg bg-surface-2 p-3"><div className="text-[10px] uppercase tracking-wide text-ink-3">{l}</div><div className="tabular display text-xl">{v}</div></div>)}{best && <button type="button" onClick={() => setOpen(best)} className="rounded-lg border border-line bg-surface-2 p-3 text-left hover:border-line-strong"><div className="text-[10px] uppercase tracking-wide text-ink-3">Best post</div><div className="truncate text-sm font-medium">{best.title}</div><div className="tabular text-xs text-good-ink">{best.metrics?.engagementRate}% engagement</div></button>}</div></div>
      <div className="card overflow-x-auto anim-fade-up"><table className="w-full min-w-[960px] text-sm"><thead className="text-[11px] uppercase tracking-wide text-ink-3"><tr className="border-b border-line">{['Post', 'Platform', 'Published', 'Reach', 'Impressions', 'Likes', 'Comments', 'Shares', 'Eng. Rate', ''].map((h) => <th key={h} className="px-3 py-2.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{posts.map((p) => <tr key={p.id} onClick={() => setOpen(p)} className="cursor-pointer border-b border-line/60 hover:bg-surface-2/60"><td className="max-w-sm px-3 py-2"><div className="flex items-center gap-2">{p.mediaDataUri && <img src={p.mediaDataUri} alt="" className="h-8 w-12 rounded object-cover" />}<span className="truncate font-medium">{p.title}</span></div></td><td className="px-3 py-2"><PlatformChip platform={p.platform} /></td><td className="px-3 py-2 text-xs">{fmtDate(p.publishedAt)}</td><td className="tabular px-3 py-2">{fmt(p.metrics?.reach)}</td><td className="tabular px-3 py-2">{fmt(p.metrics?.impressions)}</td><td className="tabular px-3 py-2">{fmt(p.metrics?.likes)}</td><td className="tabular px-3 py-2">{fmt(p.metrics?.comments)}</td><td className="tabular px-3 py-2">{fmt(p.metrics?.shares)}</td><td className={`tabular px-3 py-2 font-semibold ${(p.metrics?.engagementRate ?? 0) >= 6 ? 'text-good-ink' : ''}`}>{p.metrics?.engagementRate != null ? `${p.metrics.engagementRate}%` : '—'}</td><td className="px-3 py-2" onClick={(e) => e.stopPropagation()}><DownloadMenu compact items={[{ label: 'Metrics (CSV)', onClick: () => downloadText(`${p.id}.csv`, rowCsv(p)) }, { label: 'Caption (TXT)', onClick: () => downloadText(`${p.id}.txt`, p.content, 'text/plain') }, ...(p.mediaDataUri ? [{ label: 'Creative (SVG)', onClick: () => downloadDataUri(`${p.id}.svg`, p.mediaDataUri as string) }] : [])]} /></td></tr>)}{posts.length === 0 && <tr><td colSpan={10} className="px-3 py-8 text-center text-ink-3">Nothing published on {PLATFORM_LABEL[platform]} yet.</td></tr>}</tbody></table></div>
      <Modal open={open !== null} onClose={() => setOpen(null)} wide title={open?.title ?? ''}>{open && (
        <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div><div className="mb-1 flex items-center gap-2"><PlatformChip platform={open.platform} /><Badge tone="magenta">{open.publishMode} mode</Badge><span className="text-xs text-ink-3">{fmtDate(open.publishedAt, { month: 'long', day: 'numeric', year: 'numeric' })}</span></div>{open.mediaDataUri && <img src={open.mediaDataUri} alt="" className="mb-2 w-full rounded-lg" />}<pre className="whitespace-pre-wrap rounded-lg bg-surface-2 p-3 text-xs leading-relaxed font-sans">{open.content}</pre></div><div><div className="grid grid-cols-3 gap-2">{[['Reach', open.metrics?.reach], ['Impressions', open.metrics?.impressions], ['Likes', open.metrics?.likes], ['Comments', open.metrics?.comments], ['Shares', open.metrics?.shares], ['Eng. rate', open.metrics?.engagementRate != null ? `${open.metrics.engagementRate}%` : null]].map(([l, v]) => <div key={String(l)} className="rounded-lg bg-surface-2 p-2"><div className="text-[9px] uppercase tracking-wide text-ink-3">{l}</div><div className="tabular text-sm font-semibold">{typeof v === 'number' ? fmt(v) : v ?? '—'}</div></div>)}</div><div className="mt-3 text-xs font-semibold">Publishing history</div><ol className="mt-1 space-y-1 text-xs text-ink-2">{open.history.map((h, i) => <li key={i} className="flex gap-2"><span className="tabular text-ink-3">{i + 1}.</span>{h}</li>)}</ol></div></div>
          <div className="rounded-xl border border-accent/40 bg-accent/5 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-accent">Analytics Agent · post analysis</div><p className="mt-1 text-sm text-ink-2">{open.analysisSummary ?? 'No analysis yet — metrics have not been reported for this post.'}</p>{open.analysisRecommendation && <p className="mt-2 text-sm"><b>Recommendation:</b> {open.analysisRecommendation}</p>}<Btn size="sm" variant="ghost" className="mt-3" icon={<BookmarkPlus size={13} />} onClick={() => s.addKnowledge({ title: `Insight: ${open.title}`, category: 'High Performer', content: `${open.analysisSummary ?? ''} ${open.analysisRecommendation ?? ''}`.trim(), source: 'Analytics Agent' })}>Save insight to Knowledge Base</Btn></div></div>
      )}</Modal>
    </div>
  )
}
