import { AlertTriangle, Bot, CheckCircle2, Image as ImageIcon, RefreshCw, Send, ShieldCheck, Sparkles, X, XCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { BRAND, type BrandCheck } from '../../shared/brand-voice'
import { ModelMenu } from '../components/model-menu'
import { PlatformPreview } from '../components/previews'
import { Badge, Btn, Dialog, IDEA_STATUS_META, Modal, PLATFORM_LABEL, PlatformChip, Spinner, fmtDate } from '../components/ui'
import { checkCaption } from '../lib/ai'
import { headlineFor } from '../lib/image-gen'
import { useStore } from '../store'
import type { ChatMessage, Platform } from '../types'

const SLOTS = ['8:00 AM', '8:30 AM', '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM']
const PHASES = ['Preparing content', 'Validating platform format', 'Uploading media', 'Publishing', 'Published successfully']
const CAPTION_ACTIONS = ['Improve', 'Shorten', 'Expand', 'Change Tone', 'Add CTA']
const IMAGE_ACTIONS = ['Brighter', 'Simpler', 'More accent', 'Add depth']
const VERDICT_TONE: Record<BrandCheck['verdict'], 'good' | 'warn' | 'critical'> = { APPROVED: 'good', REVISE: 'warn', NEEDS_INTERNAL_APPROVAL: 'critical', CANNOT_VERIFY: 'warn' }

export function ReviewPanel() {
  const s = useStore(useShallow((st) => ({ id: st.reviewIdeaId, ideas: st.ideas, user: st.user, close: st.closeReview, ensureDraft: st.ensureDraft, regenerateDraft: st.regenerateDraft, regenerateImage: st.regenerateImage, instructAI: st.instructAI, updateDraft: st.updateDraft, saveDraft: st.saveDraft, setIdeaTime: st.setIdeaTime, setIdeaPlatform: st.setIdeaPlatform, approveIdea: st.approveIdea, leadershipApprove: st.leadershipApprove, publishIdea: st.publishIdea, addKnowledge: st.addKnowledge, publishPhase: st.publishPhase, publishingIdeaId: st.publishingIdeaId, imageModels: st.imageModels, apiMode: st.apiMode, settings: st.settings, updateSettings: st.updateSettings, published: st.published, publishMode: st.publishMode })))
  const idea = s.ideas.find((i) => i.id === s.id)
  const [target, setTarget] = useState<'caption' | 'image'>('caption'); const [chat, setChat] = useState<ChatMessage[]>([]); const [input, setInput] = useState(''); const [thinking, setThinking] = useState<string | null>(null)
  const [pref, setPref] = useState<{ title: string; content: string; category: string } | null>(null); const [confirm, setConfirm] = useState(false); const [prompt, setPrompt] = useState(''); const [model, setModel] = useState(s.settings.imageModel)
  const platform = idea?.platform ?? 'linkedin'
  useEffect(() => { if (idea && !idea.drafts[platform]) void s.ensureDraft(idea.id, platform) }, [idea?.id, platform]) // eslint-disable-line react-hooks/exhaustive-deps
  const draft = idea?.drafts[platform]; const media = idea?.media[platform]
  useEffect(() => { if (media?.prompt) setPrompt(media.prompt) }, [media?.prompt])
  const check = useMemo(() => (idea && draft ? checkCaption(draft.body, platform, `${idea.sourceTopic} ${idea.title}`, media ? { headline: headlineFor(draft.body, idea.title), hasAltText: Boolean(media.altText) } : undefined, s.published.slice(0, 10).map((p) => p.content)) : null), [idea, draft, media, platform, s.published])
  if (!idea) return null
  const st = IDEA_STATUS_META[idea.status]
  const publishing = s.publishingIdeaId === idea.id && s.publishPhase >= 0
  const say = (role: ChatMessage['role'], text: string) => setChat((c) => [...c, { id: Date.now() + Math.random(), role, text, at: new Date().toISOString() }])
  const send = async (text: string) => {
    if (!text.trim()) return
    say('user', text); setInput('')
    if (target === 'image') { setThinking(`Re-rendering with ${model}…`); await new Promise((r) => setTimeout(r, 900)); await s.regenerateImage(idea.id, platform, { model, instruction: text }); setThinking(null); say('assistant', `Re-rendered the ${PLATFORM_LABEL[platform]} creative with "${text}" folded into the prompt. The brand layer stays local.`); return }
    setThinking('Rewriting draft…')
    const start = Date.now(); const r = await s.instructAI(idea.id, platform, text); await new Promise((res) => setTimeout(res, Math.max(0, 900 - (Date.now() - start))))
    setThinking(null); say('assistant', `${r.note} Brand check: ${r.check.verdict}${r.check.violations.length ? ` (${r.check.violations.length} finding${r.check.violations.length > 1 ? 's' : ''})` : ''}.`)
    if (r.learnable) setPref(r.learnable)
  }
  const examples = target === 'caption' ? ['Make it shorter and close on a question', 'Add a sentence about reward hacking', 'Make it more technical', 'Replace "loop" with "cycle"'] : ['Use a calmer palette with less contrast', 'Add depth with layered gradients', 'Make the field simpler', 'Brighter and more optimistic']
  return (
    <Dialog open onClose={s.close}>
      <div className="flex items-center justify-between gap-4 border-b border-line px-5 py-3"><div className="min-w-0"><div className="display truncate text-base">{idea.title}</div><div className="text-xs text-ink-3">Calendar Review · {fmtDate(idea.date, { weekday: 'long', month: 'long', day: 'numeric' })} · {idea.time}</div></div><div className="flex items-center gap-2"><Badge tone={st.tone}>{st.label}</Badge><button type="button" onClick={s.close} className="rounded-md p-1 text-ink-3 hover:bg-surface-2 hover:text-ink" aria-label="Close"><X size={18} /></button></div></div>
      <div className="grid min-h-0 flex-1 grid-cols-[260px_1fr_300px] gap-4 overflow-hidden p-4">
        <aside className="min-h-0 space-y-3 overflow-y-auto pr-1">
          <div className="card p-3 text-xs"><div className="mb-2 text-[10px] uppercase tracking-wide text-ink-3">Content Information</div><dl className="space-y-1.5">{[['Source topic', idea.sourceTopic], ['Hashtag', idea.hashtag ? `#${idea.hashtag}` : '—'], ['Angle', idea.analysis.angle], ['Audience', idea.analysis.audience], ['Format', idea.analysis.format]].map(([k, v]) => <div key={String(k)}><dt className="text-ink-3">{k}</dt><dd className="text-ink">{v ?? '—'}</dd></div>)}</dl><div className="mt-2 grid grid-cols-2 gap-1.5">{[['Brand relevance', idea.analysis.brandRelevance], ['Trend score', idea.analysis.trendScore]].map(([k, v]) => <div key={String(k)} className="rounded bg-surface-2 px-2 py-1"><div className="text-[9px] uppercase text-ink-3">{k}</div><div className="tabular font-semibold">{v ?? '—'}%</div></div>)}</div></div>
          <div className="card p-3 text-xs"><div className="mb-2 text-[10px] uppercase tracking-wide text-ink-3">AI Recommendation</div><div className="font-medium">{fmtDate(idea.date, { weekday: 'long', month: 'short', day: 'numeric' })} · {idea.time}</div><div className="mt-1 text-ink-3">Why this slot?</div><ul className="mt-1 space-y-1 text-ink-2">{(idea.analysis.slotReasons ?? []).slice(0, 4).map((r, i) => <li key={i}>• {r}</li>)}</ul><label className="mt-2 block text-ink-3">Posting time<select value={SLOTS.includes(idea.time) ? idea.time : SLOTS[5]} onChange={(e) => s.setIdeaTime(idea.id, e.target.value)} className="mt-1 w-full py-1 text-xs">{SLOTS.map((t) => <option key={t}>{t}</option>)}</select></label></div>
          <div className="card p-3 text-xs"><div className="mb-2 text-[10px] uppercase tracking-wide text-ink-3">Platform</div><div className="flex items-center justify-between rounded-lg border border-accent/40 bg-accent/10 px-2 py-1.5"><PlatformChip platform={platform} /><span className="tabular">{idea.analysis.platformScores?.[platform] ?? '—'}% match</span></div>{idea.altPlatforms.map((a) => <button key={a.platform} type="button" onClick={() => s.setIdeaPlatform(idea.id, a.platform as Platform)} className="mt-1.5 flex w-full items-center justify-between rounded-lg border border-line px-2 py-1.5 hover:border-line-strong"><PlatformChip platform={a.platform} /><span className="tabular text-ink-3">{a.score}% match</span></button>)}</div>
        </aside>
        <section className="min-h-0 space-y-4 overflow-y-auto pr-1">
          <div className="card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-sm font-semibold">AI-Generated Post <span className="text-xs font-normal text-ink-3">· editable · rev {draft?.revision ?? 0} · {draft?.model ?? '—'}</span></div><div className="flex flex-wrap gap-1"><Btn size="sm" variant="ghost" icon={<RefreshCw size={12} />} onClick={() => s.regenerateDraft(idea.id, platform)}>Regenerate</Btn>{CAPTION_ACTIONS.map((a) => <Btn key={a} size="sm" variant="subtle" onClick={() => { setTarget('caption'); void send(a === 'Change Tone' ? 'Change the tone' : a === 'Add CTA' ? 'Add a CTA' : a) }}>{a}</Btn>)}</div></div>
            {draft ? <textarea rows={13} value={draft.body} onChange={(e) => s.updateDraft(idea.id, platform, e.target.value)} onBlur={() => s.saveDraft(idea.id, platform)} className="mt-3 w-full resize-y font-sans text-sm leading-relaxed" /> : <div className="mt-3 flex items-center gap-2 py-8 text-sm text-ink-3"><Spinner />Caption Agent is writing…</div>}
            <div className="mt-1 text-right text-[11px] text-ink-3 tabular">{draft?.body.length ?? 0} / {BRAND.platformLimits[platform]} characters</div></div>
          {check && <div className="card p-4"><div className="flex flex-wrap items-center gap-2"><ShieldCheck size={16} className={check.verdict === 'APPROVED' ? 'text-good-ink' : 'text-warn'} /><span className="text-sm font-semibold">Brand Voice check</span><Badge tone={VERDICT_TONE[check.verdict]}>{check.verdict}</Badge></div><div className="mt-2 flex flex-wrap gap-1.5">{(Object.entries(check.dimensions) as Array<[string, { ok: boolean; note: string }]>).map(([k, d]) => <span key={k} title={d.note} className={`rounded-full border px-2 py-0.5 text-[10px] capitalize ${d.ok ? 'border-good/30 bg-good/10 text-good-ink' : 'border-warn/30 bg-warn/10 text-warn'}`}>{k === 'captionVisual' ? 'Caption–visual' : k}</span>)}</div>{check.violations.length === 0 ? <p className="mt-2 text-xs text-ink-2">{check.summary}</p> : <div className="mt-2 space-y-1.5">{check.violations.map((v, i) => <div key={i} className="rounded-lg border border-line bg-surface-2 p-2 text-xs"><div className="font-medium">Rule {v.rule} · {v.title}</div><div className="text-ink-2">{v.detail}</div><div className="text-accent">→ {v.required_action}</div></div>)}{check.corrected_version && <Btn size="sm" variant="ghost" onClick={() => s.updateDraft(idea.id, platform, check.corrected_version as string)}>Apply corrected version</Btn>}</div>}</div>}
          <div className="card p-4"><div className="flex flex-wrap items-center gap-2"><ImageIcon size={16} className="text-accent" /><span className="text-sm font-semibold">Image Creator</span>{media && <><Badge>{media.canvas}</Badge><Badge>{media.concept}</Badge><Badge tone={media.model === 'brand-svg' ? 'neutral' : 'accent'}>{media.model}</Badge></>}</div>
            {media ? <img src={media.dataUri} alt={media.altText ?? ''} className="mt-3 max-h-[440px] rounded-xl border border-line" /> : <div className="mt-3 flex items-center gap-2 py-8 text-sm text-ink-3"><Spinner />Rendering…</div>}
            {media?.fallbackReason && <div className="mt-2 flex items-start gap-2 rounded-lg border border-warn/40 bg-warn/10 px-3 py-2 text-xs text-warn"><AlertTriangle size={13} className="mt-0.5 shrink-0" />{media.fallbackReason}</div>}
            <label className="mt-3 block text-xs text-ink-3">Image prompt (the brand layer — headline, logomark, footer — is always drawn locally)<textarea rows={3} value={prompt} onChange={(e) => setPrompt(e.target.value)} className="mt-1 w-full text-xs" /></label>
            <div className="mt-2 flex flex-wrap gap-1"><Btn size="sm" variant="primary" icon={<RefreshCw size={12} />} onClick={() => s.regenerateImage(idea.id, platform, { model, prompt })}>Re-render</Btn>{IMAGE_ACTIONS.map((a) => <Btn key={a} size="sm" variant="subtle" onClick={() => { setTarget('image'); void send(a) }}>{a}</Btn>)}</div>
            {media?.altText && <div className="mt-2 text-[11px] text-ink-3"><b>Alt text:</b> {media.altText}</div>}</div>
          <div><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-ink-3">Live preview · {PLATFORM_LABEL[platform]}</div><div className="max-w-xl"><PlatformPreview platform={platform} caption={draft?.body ?? ''} media={media} /></div></div>
        </section>
        <aside className="flex min-h-0 flex-col gap-3 overflow-y-auto pr-1">
          <div className="card flex min-h-[420px] flex-1 flex-col p-3">
            <div className="flex items-center justify-between"><div className="flex items-center gap-1.5 text-sm font-semibold"><Bot size={15} className="text-accent" />AI Assistant</div><div className="inline-flex rounded-full border border-line bg-surface-2 p-0.5 text-[11px]">{(['caption', 'image'] as const).map((t) => <button key={t} type="button" onClick={() => setTarget(t)} className={`rounded-full px-2.5 py-0.5 capitalize ${target === t ? 'bg-accent text-on-accent' : 'text-ink-2'}`}>{t}</button>)}</div></div>
            <div className="mt-2 min-h-0 flex-1 space-y-2 overflow-y-auto">{chat.length === 0 && <div className="space-y-1.5">{examples.map((e) => <button key={e} type="button" onClick={() => send(e)} className="block w-full rounded-lg border border-line bg-surface-2 px-2.5 py-1.5 text-left text-[11px] text-ink-2 hover:text-ink">{e}</button>)}</div>}{chat.map((m) => <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : ''}`}><div className={`max-w-[90%] rounded-xl px-2.5 py-1.5 text-[12px] anim-pop-in ${m.role === 'user' ? 'bg-accent/20' : 'bg-surface-2 text-ink-2'}`}>{m.text}</div></div>)}{thinking && <div className="flex items-center gap-2 text-[11px] text-ink-3"><Spinner />{thinking}</div>}
              {pref && <div className="rounded-lg border border-magenta/40 bg-magenta/10 p-2.5 text-[11px] anim-pop-in"><div className="flex items-center gap-1 font-medium"><Sparkles size={11} className="text-magenta-ink" />Save this preference to the Knowledge Base?</div><div className="mt-0.5 text-ink-2">{pref.title} — {pref.content}</div><div className="mt-1.5 flex gap-1.5"><Btn size="sm" variant="primary" onClick={() => { void s.addKnowledge({ ...pref, source: 'Review Agent' }); setPref(null) }}>Save</Btn><Btn size="sm" variant="ghost" onClick={() => setPref(null)}>Dismiss</Btn></div></div>}</div>
            <form onSubmit={(e) => { e.preventDefault(); void send(input) }} className="mt-2 flex gap-1.5"><input value={input} onChange={(e) => setInput(e.target.value)} placeholder={target === 'caption' ? 'Tell the Review Agent what to change…' : 'Describe the creative…'} className="flex-1 text-xs" /><Btn size="sm" variant="primary" type="submit" disabled={!input.trim() || thinking !== null} aria-label="Send"><Send size={13} /></Btn></form>
            <div className="mt-2"><ModelMenu mode={target} value={model} onChange={(m) => { setModel(m); s.updateSettings({ imageModel: m }); void s.regenerateImage(idea.id, platform, { model: m, prompt }) }} models={s.imageModels} connected={s.apiMode === 'live'} /></div>
          </div>
          <div className="card border-accent/40 p-3"><div className="mb-2 text-[10px] uppercase tracking-wide text-accent">Final Approval</div>
            {publishing ? <div className="space-y-1.5 text-xs">{PHASES.map((p, i) => <div key={p} className={`flex items-center gap-2 ${i <= s.publishPhase ? 'text-ink' : 'text-ink-3'}`}>{i < s.publishPhase ? <CheckCircle2 size={13} className="text-good-ink" /> : i === s.publishPhase ? <Spinner size={12} /> : <span className="h-3 w-3 rounded-full border border-line" />}{p}</div>)}</div>
              : idea.status === 'rejected' ? <div className="text-xs"><Badge tone="critical"><XCircle size={11} /> Rejected</Badge><p className="mt-1 italic text-ink-3">"{idea.leadershipDecision?.reason}"</p></div>
              : idea.status === 'published' ? <Badge tone="good">Published</Badge>
              : idea.status === 'approved' ? <div className="space-y-2"><Btn variant="primary" className="w-full" icon={<Send size={14} />} onClick={() => setConfirm(true)}>Publish Now</Btn><Btn variant="ghost" className="w-full" onClick={() => setConfirm(true)}>Schedule for {idea.time}</Btn></div>
              : idea.status === 'pending_leadership' ? (s.user?.role === 'leadership' ? <Btn variant="primary" className="w-full" icon={<CheckCircle2 size={14} />} onClick={() => s.leadershipApprove(idea.id)}>Give final approval</Btn> : <div className="rounded-lg bg-surface-2 p-2.5 text-xs text-ink-2">Approved by <b>{idea.marketingApprovedBy}</b>. Waiting for Leadership's final decision — nothing publishes until then.</div>)
              : <Btn variant="primary" className="w-full" icon={<CheckCircle2 size={14} />} onClick={() => s.approveIdea(idea.id)}>Approve &amp; send to Leadership</Btn>}
          </div>
        </aside>
      </div>
      <Modal open={confirm} onClose={() => setConfirm(false)} wide title="Publish this post?" footer={<div className="flex justify-end gap-2"><Btn variant="ghost" onClick={() => setConfirm(false)}>Cancel</Btn><Btn variant="primary" onClick={() => { setConfirm(false); void s.publishIdea(idea.id) }}>Publish now</Btn></div>}><div className="mb-3 flex flex-wrap gap-2"><PlatformChip platform={platform} /><Badge>{fmtDate(idea.date)} · {idea.time}</Badge>{s.publishMode === 'demo' ? <Badge tone="warn">Demo publish mode — the receipt is recorded without dispatching</Badge> : <Badge tone="good">Live dispatch</Badge>}</div><PlatformPreview platform={platform} caption={draft?.body ?? ''} media={media} /></Modal>
    </Dialog>
  )
}
